const STORAGE_ORDERS = 'pedidos_kit_orders_v1';
const catalogProducts = [
  ['sporting-home','Sporting CP Principal 26/27','Sporting CP','Principal','Camisola','Portugal',20,'NOVA ÉPOCA','assets/catalogo-26-27/sporting-principal.webp'],
  ['sporting-special','Sporting 120 Anos Especial 2026','Sporting CP','Especial','Camisola','Especial',20,'ESPECIAL','assets/catalogo-26-27/sporting-especial.webp'],
  ['benfica-home','SL Benfica Principal 26/27','Benfica','Principal','Camisola','Portugal',20,'NOVA ÉPOCA','assets/catalogo-26-27/benfica-principal.webp'],
  ['benfica-away','SL Benfica Alternativo 26/27','Benfica','Secundário','Camisola','Portugal',20,'NOVA ÉPOCA','assets/catalogo-26-27/benfica-alternativa.webp'],
  ['porto-home','FC Porto Principal 26/27','FC Porto','Principal','Camisola','Portugal',20,'NOVA ÉPOCA','assets/catalogo-26-27/porto-principal.webp'],
  ['porto-away','FC Porto Alternativo 26/27','FC Porto','Secundário','Camisola','Portugal',20,'NOVA ÉPOCA','assets/catalogo-26-27/porto-alternativa.webp'],
  ['porto-third','FC Porto Terceiro 26/27','FC Porto','Terciário','Camisola','Portugal',20,'NOVA ÉPOCA','assets/catalogo-26-27/porto-terceira.webp'],
  ['porto-special','FC Porto Edição Especial 2026','FC Porto','Especial','Camisola','Especial',20,'ESPECIAL','assets/catalogo-26-27/porto-especial.webp'],
  ['porto-kids-home','Kit Criança FC Porto Principal 26/27','FC Porto','Principal','Kit','Criança',23,'KIDS','assets/catalogo-26-27/porto-kids-principal.webp'],
  ['porto-kids-away','Kit Criança FC Porto Alternativo 26/27','FC Porto','Secundário','Kit','Criança',23,'KIDS','assets/catalogo-26-27/porto-kids-alternativa.webp'],
  ['porto-kids-third','Kit Criança FC Porto Terceiro 26/27','FC Porto','Terciário','Kit','Criança',23,'KIDS','assets/catalogo-26-27/porto-kids-terceira.webp'],
  ['madrid-home','Real Madrid Principal 26/27','Real Madrid','Principal','Camisola','Europa',20,'NOVA ÉPOCA','assets/catalogo-26-27/real-madrid-principal.webp'],
  ['madrid-away','Real Madrid Alternativo 26/27','Real Madrid','Secundário','Camisola','Europa',20,'NOVA ÉPOCA','assets/catalogo-26-27/real-madrid-alternativa.webp'],
  ['barca-home','FC Barcelona Principal 26/27','FC Barcelona','Principal','Camisola','Europa',20,'NOVA ÉPOCA','assets/catalogo-26-27/barcelona-principal.webp'],
  ['psg-home','Paris Saint-Germain Principal 26/27','Paris Saint-Germain','Principal','Camisola','Europa',20,'NOVA ÉPOCA','assets/catalogo-26-27/psg-principal.webp'],
  ['portugal-home','Portugal Principal 2026','Seleção de Portugal','Principal','Camisola','Seleções',20,'SELEÇÃO','https://images.unsplash.com/photo-1606925797300-0b35e9d1794e?auto=format&fit=crop&w=700&q=85'],
  ['brazil-home','Brasil Principal 2026','Seleção do Brasil','Principal','Camisola','Seleções',20,'SELEÇÃO','https://images.unsplash.com/photo-1508098682722-e99c43a406b2?auto=format&fit=crop&w=700&q=85']
].map(([id,name,club,equipment,type,group,price,tag,image]) => ({ id,name,club,equipment,type,group,price,tag,image }));
const productImageVariants = {
  'sporting-home': { front: 'assets/catalogo-26-27/sporting-principal-frente.webp', back: 'assets/catalogo-26-27/sporting-principal.webp' },
  'benfica-home': { front: 'assets/catalogo-26-27/benfica-principal-frente.webp', back: 'assets/catalogo-26-27/benfica-principal.webp' },
  'porto-home': { front: 'assets/catalogo-26-27/porto-principal-frente.webp', back: 'assets/catalogo-26-27/porto-principal.webp' }
};
let catalogFilter = 'Todos', cart = [], selectedProduct = null;
const euro = value => `${Number(value).toFixed(2).replace('.', ',')} EUR`;
function resolveProductImages(product) {
  const variant = productImageVariants[product.id];
  if (variant) return variant;
  return { front: product.image, back: product.image };
}
function productMarkup(product) {
  const { front, back } = resolveProductImages(product);
  return `<article class="product" data-product-id="${product.id}"><div class="product-image"><img class="product-photo product-photo-front" src="${front}" alt="${product.name}" loading="lazy" onmouseover="this.style.opacity='0'; this.parentNode.querySelector('.product-photo-back').style.opacity='1';" onmouseout="this.style.opacity='1'; this.parentNode.querySelector('.product-photo-back').style.opacity='0';"><img class="product-photo product-photo-back" src="${back}" alt="${product.name} visto por trás" loading="lazy" onmouseover="this.style.opacity='1'; this.parentNode.querySelector('.product-photo-front').style.opacity='0';" onmouseout="this.style.opacity='0'; this.parentNode.querySelector('.product-photo-front').style.opacity='1';"><span class="product-tag">${product.tag}</span></div><div class="product-info"><p class="product-name">${product.name}</p><p class="product-price">${euro(product.price)}</p><p class="product-category">${product.group} / ${product.equipment}</p></div><button class="product-add" data-product-id="${product.id}" type="button">ESCOLHER TAMANHO</button></article>`; }
function renderCatalog() { const sort = document.getElementById('catalog-sort').value; const listed = catalogProducts.filter(product => catalogFilter === 'Todos' || product.group === catalogFilter).sort((a,b) => sort === 'low' ? a.price - b.price : sort === 'high' ? b.price - a.price : 0); document.getElementById('catalog-grid').innerHTML = listed.map(productMarkup).join(''); document.getElementById('catalog-count').textContent = catalogProducts.length; document.getElementById('catalog-result').textContent = `A mostrar ${listed.length} ${listed.length === 1 ? 'produto' : 'produtos'}`; }
function renderCart() { const total = cart.reduce((sum,item) => sum + item.product.price,0); document.getElementById('cart-count').textContent = cart.length; document.getElementById('cart-total').textContent = euro(total); document.getElementById('checkout-button').disabled = !cart.length; document.getElementById('cart-items').innerHTML = cart.length ? cart.map((item,index) => `<div class="cart-item"><img src="${item.product.image}" alt=""><div><p>${item.product.name}</p><small>TAM. ${item.size}${item.customName ? ` / ${item.customName}${item.customNumber ? ' #' + item.customNumber : ''}` : ''}</small><small>${euro(item.product.price)}</small></div><button class="remove-item" data-index="${index}" type="button" aria-label="Remover artigo">x</button></div>`).join('') : '<p class="cart-empty">O teu carrinho ainda está vazio.</p>'; }
function showToast(message) { const toast = document.getElementById('toast'); toast.textContent = message; toast.classList.add('show'); clearTimeout(showToast.timer); showToast.timer = setTimeout(() => toast.classList.remove('show'),2800); }
function toggleCart(show) { document.getElementById('cart-drawer').classList.toggle('open',show); document.getElementById('cart-drawer').setAttribute('aria-hidden',String(!show)); document.getElementById('overlay').hidden = !show; }
document.addEventListener('click', event => { const add = event.target.closest('[data-product-id]'); if (add) { selectedProduct = catalogProducts.find(product => product.id === add.dataset.productId); document.getElementById('product-dialog-title').innerHTML = `${selectedProduct.club.toUpperCase()}<br>ESCOLHE O TAMANHO`; document.getElementById('product-form').reset(); document.getElementById('product-custom-fields').hidden = true; document.getElementById('product-dialog').showModal(); } const remove = event.target.closest('.remove-item'); if (remove) { cart.splice(Number(remove.dataset.index),1); renderCart(); } });
document.getElementById('catalog-filters').addEventListener('click', event => { const filter = event.target.closest('.catalog-filter'); if (!filter) return; catalogFilter = filter.dataset.filter; document.querySelectorAll('.catalog-filter').forEach(button => button.classList.toggle('active',button === filter)); renderCatalog(); });
document.getElementById('catalog-sort').addEventListener('change',renderCatalog); document.getElementById('open-cart').addEventListener('click',() => toggleCart(true)); document.getElementById('close-cart').addEventListener('click',() => toggleCart(false)); document.getElementById('overlay').addEventListener('click',() => toggleCart(false)); document.getElementById('close-product').addEventListener('click',() => document.getElementById('product-dialog').close()); document.getElementById('close-checkout').addEventListener('click',() => document.getElementById('checkout-dialog').close());
document.getElementById('product-custom').addEventListener('change',event => document.getElementById('product-custom-fields').hidden = !event.target.checked); document.getElementById('product-form').addEventListener('submit',event => { event.preventDefault(); const isCustom = document.getElementById('product-custom').checked; cart.push({ product:selectedProduct,size:document.getElementById('product-size').value,customName:isCustom ? document.getElementById('product-custom-name').value.trim() : '',customNumber:isCustom ? document.getElementById('product-custom-number').value.trim() : '' }); document.getElementById('product-dialog').close(); renderCart(); showToast('Artigo adicionado ao carrinho.'); });
document.getElementById('checkout-button').addEventListener('click',() => { if (cart.length) document.getElementById('checkout-dialog').showModal(); }); document.getElementById('checkout-form').addEventListener('submit',event => { event.preventDefault(); const name = document.getElementById('customer-name').value.trim(), phone = document.getElementById('customer-phone').value.trim(), note = document.getElementById('customer-note').value.trim(); let orders; try { orders = JSON.parse(localStorage.getItem(STORAGE_ORDERS)) || []; } catch { orders = []; } orders.push(...cart.map(item => ({ id:crypto.randomUUID(),nome:name,telemovel:phone,tipo:item.product.type,clube:item.product.club,equipamento:item.product.equipment,tamanho:item.size,customizado:Boolean(item.customName || item.customNumber),customNome:item.customName,customNumero:item.customNumber,patchado:false,patchNome:'',preco:item.product.price,custo:0,pago:false,entregue:false,observacoes:note ? `Pedido SARD online: ${note}` : 'Pedido SARD online',createdAt:Date.now() }))); localStorage.setItem(STORAGE_ORDERS,JSON.stringify(orders)); cart=[]; renderCart(); event.target.reset(); document.getElementById('checkout-dialog').close(); toggleCart(false); showToast('Pedido recebido. Obrigado por jogares connosco.'); });
renderCatalog(); renderCart();