const STORAGE_ORDERS = 'pedidos_kit_orders_v1';
const products = [
  { id:'porto-home', name:'FC Porto Principal 26/27', club:'FC Porto', equipment:'Principal', type:'Camisola', group:'Portugal', price:25, tag:'NOVA EPOCA', image:'https://images.unsplash.com/photo-1553778263-73a83bab9b0c?auto=format&fit=crop&w=700&q=85' },
  { id:'benfica-home', name:'SL Benfica Principal 26/27', club:'Benfica', equipment:'Principal', type:'Camisola', group:'Portugal', price:25, tag:'NOVA EPOCA', image:'https://images.unsplash.com/photo-1560272564-c83b66b1ad12?auto=format&fit=crop&w=700&q=85' },
  { id:'sporting-away', name:'Sporting CP Alternativo 26/27', club:'Sporting CP', equipment:'Secundário', type:'Camisola', group:'Portugal', price:25, tag:'DROP 01', image:'https://images.unsplash.com/photo-1570498839593-e565b39455fc?auto=format&fit=crop&w=700&q=85' },
  { id:'madrid-away', name:'Real Madrid Alternativo 26/27', club:'Real Madrid', equipment:'Secundário', type:'Camisola', group:'Europa', price:27, tag:'DROP 01', image:'https://images.unsplash.com/photo-1540747913346-19e32dc3e97e?auto=format&fit=crop&w=700&q=85' },
  { id:'barcelona-home', name:'FC Barcelona Principal 26/27', club:'FC Barcelona', equipment:'Principal', type:'Camisola', group:'Europa', price:27, tag:'NOVA EPOCA', image:'https://images.unsplash.com/photo-1552318965-6e6be7484ada?auto=format&fit=crop&w=700&q=85' },
  { id:'portugal-home', name:'Portugal Principal 2026', club:'Seleção de Portugal', equipment:'Principal', type:'Camisola', group:'Selecoes', price:23, tag:'SELECAO', image:'https://images.unsplash.com/photo-1606925797300-0b35e9d1794e?auto=format&fit=crop&w=700&q=85' },
  { id:'brazil-away', name:'Brasil Alternativo 2026', club:'Seleção do Brasil', equipment:'Secundário', type:'Camisola', group:'Selecoes', price:23, tag:'SELECAO', image:'https://images.unsplash.com/photo-1508098682722-e99c43a406b2?auto=format&fit=crop&w=700&q=85' },
  { id:'inter-retro', name:'Inter 1998/99', club:'Inter Milan', equipment:'Retro', type:'Camisola', group:'Retro', price:29, tag:'RETRO', image:'https://images.unsplash.com/photo-1517466787929-bc90951d0974?auto=format&fit=crop&w=700&q=85' },
  { id:'milan-retro', name:'AC Milan 2006/07', club:'AC Milan', equipment:'Retro', type:'Camisola', group:'Retro', price:29, tag:'RETRO', image:'https://images.unsplash.com/photo-1577223625816-7546f13df25d?auto=format&fit=crop&w=700&q=85' },
  { id:'arsenal-retro', name:'Arsenal 2002/03', club:'Arsenal', equipment:'Retro', type:'Camisola', group:'Retro', price:29, tag:'RETRO', image:'https://images.unsplash.com/photo-1526232761682-d26e03ac148e?auto=format&fit=crop&w=700&q=85' },
  { id:'porto-retro', name:'FC Porto 2003/04', club:'FC Porto', equipment:'Retro', type:'Camisola', group:'Retro', price:29, tag:'RETRO', image:'https://images.unsplash.com/photo-1580087433295-ab2600c1030e?auto=format&fit=crop&w=700&q=85' }
];
let cart = [];
let selectedProduct = null;
const euro = value => `${Number(value).toFixed(2).replace('.', ',')} EUR`;
const productMarkup = product => `<article class="product"><div class="product-image"><img src="${product.image}" alt="${product.name}" loading="lazy"><span class="product-tag">${product.tag}</span></div><div class="product-info"><p class="product-name">${product.name}</p><p class="product-price">${euro(product.price)}</p><p class="product-category">${product.group} / ${product.equipment}</p></div><button class="product-add" type="button" data-product-id="${product.id}">ADICIONAR AO CARRINHO</button></article>`;
function renderProducts(filter = 'Todos') { document.getElementById('product-grid').innerHTML = products.filter(product => product.group !== 'Retro' && (filter === 'Todos' || product.group === filter)).map(productMarkup).join(''); document.getElementById('retro-grid').innerHTML = products.filter(product => product.group === 'Retro').map(productMarkup).join(''); }
function renderCart() { const container = document.getElementById('cart-items'); const total = cart.reduce((sum, item) => sum + item.product.price, 0); document.getElementById('cart-count').textContent = cart.length; document.getElementById('cart-total').textContent = euro(total); document.getElementById('checkout-button').disabled = !cart.length; container.innerHTML = cart.length ? cart.map((item, index) => `<div class="cart-item"><img src="${item.product.image}" alt=""><div><p>${item.product.name}</p><small>TAM. ${item.size}${item.customName ? ` / ${item.customName} ${item.customNumber ? '#' + item.customNumber : ''}` : ''}</small><small>${euro(item.product.price)}</small></div><button class="remove-item" data-index="${index}" type="button" aria-label="Remover artigo">×</button></div>`).join('') : '<p class="cart-empty">O teu carrinho ainda está vazio.</p>'; }
function addProduct(productId) { selectedProduct = products.find(item => item.id === productId); document.getElementById('product-dialog-title').innerHTML = `${selectedProduct.name.split(' ').slice(0, 2).join(' ')}<br>ESCOLHE O TAMANHO`; document.getElementById('product-form').reset(); document.getElementById('product-custom-fields').hidden = true; document.getElementById('product-dialog').showModal(); }
function toggleCart(show) { const drawer = document.getElementById('cart-drawer'); drawer.classList.toggle('open', show); drawer.setAttribute('aria-hidden', String(!show)); document.getElementById('overlay').hidden = !show; }
let toastTimer; function showToast(message) { const toast = document.getElementById('toast'); toast.textContent = message; toast.classList.add('show'); clearTimeout(toastTimer); toastTimer = setTimeout(() => toast.classList.remove('show'), 2800); }
document.addEventListener('click', event => { const button = event.target.closest('[data-product-id]'); if (button) addProduct(button.dataset.productId); const remove = event.target.closest('.remove-item'); if (remove) { cart.splice(Number(remove.dataset.index), 1); renderCart(); } });
document.getElementById('filters').addEventListener('click', event => { const button = event.target.closest('.filter'); if (!button) return; document.querySelectorAll('.filter').forEach(item => item.classList.toggle('active', item === button)); renderProducts(button.dataset.filter); });
document.getElementById('open-cart').addEventListener('click', () => toggleCart(true)); document.getElementById('close-cart').addEventListener('click', () => toggleCart(false)); document.getElementById('overlay').addEventListener('click', () => toggleCart(false));
document.getElementById('checkout-button').addEventListener('click', () => { if (cart.length) document.getElementById('checkout-dialog').showModal(); }); document.getElementById('close-checkout').addEventListener('click', () => document.getElementById('checkout-dialog').close());
document.getElementById('close-product').addEventListener('click', () => document.getElementById('product-dialog').close());
document.getElementById('product-custom').addEventListener('change', event => { document.getElementById('product-custom-fields').hidden = !event.target.checked; });
document.getElementById('product-form').addEventListener('submit', event => { event.preventDefault(); const custom = document.getElementById('product-custom').checked; cart.push({ product:selectedProduct, size:document.getElementById('product-size').value, customName:custom ? document.getElementById('product-custom-name').value.trim() : '', customNumber:custom ? document.getElementById('product-custom-number').value.trim() : '' }); document.getElementById('product-dialog').close(); renderCart(); showToast('Artigo adicionado ao carrinho.'); });
document.getElementById('checkout-form').addEventListener('submit', event => { event.preventDefault(); const name = document.getElementById('customer-name').value.trim(); const phone = document.getElementById('customer-phone').value.trim(); const note = document.getElementById('customer-note').value.trim(); const existing = (() => { try { return JSON.parse(localStorage.getItem(STORAGE_ORDERS)) || []; } catch { return []; } })(); const newOrders = cart.map(item => ({ id: crypto.randomUUID(), nome:name, telemovel:phone, tipo:item.product.type, clube:item.product.club, equipamento:item.product.equipment, tamanho:item.size, customizado:Boolean(item.customName || item.customNumber), customNome:item.customName, customNumero:item.customNumber, patchado:false, patchNome:'', preco:item.product.price, custo:0, pago:false, entregue:false, observacoes:note ? `Pedido SARD online: ${note}` : 'Pedido SARD online', createdAt:Date.now() })); localStorage.setItem(STORAGE_ORDERS, JSON.stringify([...existing, ...newOrders])); cart = []; renderCart(); event.target.reset(); document.getElementById('checkout-dialog').close(); toggleCart(false); showToast('Pedido recebido. Obrigado por jogares connosco.'); });
document.getElementById('newsletter-form').addEventListener('submit', event => { event.preventDefault(); document.getElementById('newsletter-feedback').textContent = 'Estás na lista. Até ao próximo drop.'; event.target.reset(); });
renderProducts(); renderCart();